# Generated by Django 6.0.6 on 2026-07-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_categoria_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenproducto',
            name='es_principal',
            field=models.BooleanField(default=False),
        ),
    ]
