# Generated by Django 6.0.6 on 2026-08-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_rename_fecha_registro_cliente_fecha_creacion_and_more'),
        ('pedidos', '0003_detallepedido_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='pedido_total_no_negativo'),
        ),
    ]
