# Generated by Django 6.0.6 on 2026-08-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_rename_fecha_registro_cliente_fecha_creacion_and_more'),
        ('pedidos', '0004_pedido_pedido_total_no_negativo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='pedido_subtotal_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('costo_envio__gte', 0)), name='pedido_costo_envio_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('descuento__gte', 0)), name='pedido_descuento_no_negativo'),
        ),
    ]
