# Generated by Django 6.0.6 on 2026-08-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_imagenproducto_es_principal'),
        ('pedidos', '0005_pedido_pedido_subtotal_no_negativo_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 1)), name='detalle_cantidad_positiva'),
        ),
    ]
