# Generated by Django 6.0.6 on 2026-08-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_imagenproducto_es_principal'),
        ('pedidos', '0006_detallepedido_detalle_cantidad_positiva'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='detalle_precio_unitario_no_negativo'),
        ),
    ]
