# Generated by Django 6.0.6 on 2026-08-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_rename_fecha_registro_cliente_fecha_creacion_and_more'),
        ('pedidos', '0007_detallepedido_detalle_precio_unitario_no_negativo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'PE')), fields=('cliente',), name='unique_pedido_pendiente_por_clliente'),
        ),
    ]
