# Generated by Django 6.0.6 on 2026-08-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_rename_fecha_registro_cliente_fecha_creacion_and_more'),
        ('pedidos', '0008_pedido_unique_pedido_pendiente_por_clliente'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pedido',
            name='unique_pedido_pendiente_por_clliente',
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'PE')), fields=('cliente',), name='unique_pedido_pendiente_por_cliente'),
        ),
    ]
