# Generated by Django 6.0.6 on 2026-08-10 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_direccion_options_and_more'),
        ('pedidos', '0009_remove_pedido_unique_pedido_pendiente_por_clliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.direccion'),
        ),
    ]
