# Generated by Django 6.0.6 on 2026-08-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_alter_pago_pedido'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'PE')), fields=('pedido',), name='unique_pago_pendiente_por_pedido'),
        ),
    ]
