# Generated by Django 6.0.6 on 2026-09-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_pago_unique_pago_pendiente_por_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('PR', 'En preparación'), ('EN', 'Enviado'), ('ET', 'Entregado'), ('CA', 'Cancelado')], default='PE', max_length=2),
        ),
    ]
