# Generated by Django 6.0.6 on 2026-08-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_rename_fecha_registro_cliente_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'ordering': ['-es_principal', '-fecha_creacion'], 'verbose_name': 'Dirección', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AddConstraint(
            model_name='direccion',
            constraint=models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('cliente',), name='unique_direccion_principal_por_cliente'),
        ),
    ]
